apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - tls-option.yaml
  - tls-store.yaml
secretGenerator:
  - name: cloudflare-origin-pull-ca
    files:
      - tls.ca=cloudflare-origin-pull-ca.pem
    type: Opaque
    options:
      disableNameSuffixHash: true
