apiVersion: ENC[AES256_GCM,data:Fn0=,iv:SVzPT8fx3HMYPOrOr1lt7u0Om16xGMTM77HXdoolwtU=,tag:0ammtU28wGOQzykzSB5F3w==,type:str]
kind: ENC[AES256_GCM,data:izQ/Qf53,iv:6DB3EHUsh2KMu5MkhGR9iV1DMBM/fDHphcx7lL9tk+c=,tag:qa0iQNo9PboJCCXG/rfrGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uUbMYL+kfKPmNl/b8g==,iv:T3KWFNTjeIYULlaSkxHyOVNng8AXjx8NMj14ZRHE2u8=,tag:8XytdYIQpL8mttfmHBmkcg==,type:str]
    namespace: ENC[AES256_GCM,data:YKA/uTXOkTV3xZhjug==,iv:T55za68Qrx8PESS7koPElORxkNmKftuO7zQ6adfBabg=,tag:yYAlsd9pWxEyrZqHzj4z9w==,type:str]
type: ENC[AES256_GCM,data:eP+GoSDl,iv:eT38YIyTQ8U26ICeS2R1KU1yBLrtANVf574FWDRKSHI=,tag:jUU9yKpA6LeocXZQh3dNEA==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:74QO+NCJKynHKzC8MXx3COdANHl0Ijwq5OWNK33yk7bRGLIgvVXmKI1dBo72muQLhbIM5ih7lxaR8YtP/6NxzImd9I3uBIm8hEj/Kx7R1Vxgtiuab23swE4kVm+IdUWc6fdcmjNCH5wHYGVW9u0/6U3M5iluT+ZMXE0PE90lgkUZ40leRtQZfQolfRnMFg==,iv:iFZ91xMVapEDwkb23Fq4k/a8J905KgVfqTV6Ypi/cJE=,tag:uwsJ1BKwVmsNeH/jE3RmUQ==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFczRCQ0Nob2NGUGlxZENR
            K0N3RG43ckp0b3o4bERWNit5Z2xTcTFUZkhBClc0VXNkdXNTaXRocVpsYkk2LzVw
            c09jMGVXQWlXajIvTG00eTFaajh0R1EKLS0tIEhrL3VkTXd1U3J1MlFsMjhKazVI
            ZmZlb2UyVHBuVksxblVzZEZyVjFyRXcKAC8BWczJTocwo57UqfheJrg5ODo6Xdk/
            /H6Pkpc4/iTBs8rMqG7h/j1JLv7gNdjeYHQsoSkxFxcT/HhpnixgBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YXpwWTdGVldnQkpXTXJO
            eU1WUGM5d2hTUGJpcE1ONUJiZytYdDNWbTBJCmFkQnZUV2FtVndESWJsRGdnK2xX
            QUt0UVY1S296d0xJZDlteDVzbGZkUkUKLS0tIGEyb3VzM0pua0JSdjBLSS9DbkV5
            THI0U1VjdS9DbEgrZVE1bTZlUjlMN3cKaxy+fI9mM9fc5WUXLpx6x4mMqxhmWl3G
            Z+FKEcujSdrqw4+6IAZIfCUImd8bmV5CWAoncW8bMjlKtrkC47GOpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T15:12:57Z"
    mac: ENC[AES256_GCM,data:fe9A31fWSviSxCqFIT1qtkIFNMCr11r8nw9DnsdjWmMNNJWr72rquzHqhScXr5I7dY5EpKZRhtXzjbedn1gRH8JYVx5ZMPRxBXtZzdjSYQ3aKhS63Ofukl3CHc3r5NZxQNcJMxHEXpnVYrH53ar/MF2/HfQpgw/0ATA+I7BddiM=,iv:sADXspgFgRePpmATqamxqvko0kDeUHlcOyyjdTaErt0=,tag:3wMp+F2NhPafN82WAmEjCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
