apiVersion: ENC[AES256_GCM,data:eAE=,iv:Nq49qDnsgWQb92x2q0QLACxy2/MqmTGxhiMdz9Zs8lQ=,tag:ui2Uk3QRhMmZncEzvA/bkA==,type:str]
kind: ENC[AES256_GCM,data:WoMQkzMz,iv:4syrQZh8Vmsl3WnUtuWyvsv+1bl8zX8/vZ21mvsvaTI=,tag:maoZDYpokwlfzqGj53i/bA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZhP5QhNgPYQawbiYDr0=,iv:49Cjzp9LveZNfYIe0vgoE/ANQpU9YBD49RQr5Ztz9sY=,tag:1k0kdwEPnb4/VYzoM9TyAw==,type:str]
    namespace: ENC[AES256_GCM,data:MY9sEBebcv0=,iv:Dz557ULU2tBeSuEZxq6bbyThBj3qE7xBdW10AULpQss=,tag:rPiTA4li5wQlt+fLn/+DGA==,type:str]
    annotations:
        #ENC[AES256_GCM,data:0e0YeUjOOxaeyQNJDyM7z3AcbNgIGxFp7NoJgETuD0qLxnynKOOJYF8BlCYgth4eZEzrDia27Uhd+Zsr6UyPdiOa,iv:sLItmjHSYTFXZjyM6FrKTik0VzDpvacb6zcP5i/ctiI=,tag:aWzNuxEWBECqzRDMBKTuGA==,type:comment]
        #ENC[AES256_GCM,data:hA2S6FGISiAReDjM8OqhtbNmQpSJ/cP/VbG2Edo1GoV7xjaLzbk6PYpGP0SIuEVz4PoTcYEgh1ubRv6sgA==,iv:markitWneKkq3iLLZQZcWiYHavZ1/PBRIkBQ30gTNG8=,tag:LYqoBOUjhOUmKNivvsTwIw==,type:comment]
        #ENC[AES256_GCM,data:s+IyOb52it+ehivBbPeoByssiCr9a/FX/vsobnNrEtGGIKmvBgZIGKM3Q4dS4Kl+SeFqlVffExrk9Y5JqaHJ,iv:ggfQJUydaAP83US8bj50nWqnbK8rlRYs2bb1TBfa4lk=,tag:es3Y3Orrp6i1UI2Ev6HYtw==,type:comment]
        #ENC[AES256_GCM,data:Hjvt4BzV6jlsCIduL3kIwwvIq1ttmEWQCe1Y3X7dZIJ6wJCjGSkGrlk=,iv:jagfDUJjn3p4dJyZMscEc7HjGkXr1x4znIkdFPdoY98=,tag:gU/Ec6L8a9uzfqwYD2vI1w==,type:comment]
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:sTspmg==,iv:vgj+2PETMyYXr7qiwr256sQrc+YxyJCB3xNAP+N0FLI=,tag:UR6YpXzPYnnrlQl034zT4g==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ENC[AES256_GCM,data:j2URjF8=,iv:4QYBVfh42nHdWLe4UG7kvVO3755vD+pNBATlauveo9c=,tag:fNRG2GWonLH61sKas+XqNA==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:b3W3xw==,iv:QHHBAKBLh94OBZQjyj+/NDYh6V9Wt6F0qNbK6ysfJ8g=,tag:lP85fqYSkPnEvGn9+BaT1A==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:VYNE0vw=,iv:DLB1lN1DxlPd6rzeETWK7a7A3c8T4ybXCpyrTVkHCmM=,tag:cqZCvEOJrVO+bvmMcn7BEA==,type:str]
type: ENC[AES256_GCM,data:lPXidmMG,iv:t7i8w8nG2v1xHYh+arKRnD8JW3vPIwKX3HaflHnbvo8=,tag:f7/ByJVEkVYJIZDVdGckAQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:2nuHDJIBnW20QK1D/FBJfaUHLtnKsHC1,iv:3quQhhMk3p7g5jRKdXECe6Yv4tkZPgzHJa+vEWvvHl8=,tag:ARNXs8oq6a+GsGFeW/JQfA==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa21VNU45elJaTzBCSUIx
            TFk1aUIvcGhjTnJnL3JDWDQ1Y0VBN3JGcmtVCjFwbEtXeDN5TFk3WnJxRjVNdG55
            dEtXZ0tKQmdONUZxQmFELzNmMW0waHcKLS0tIG9RRUpJUHIzNVlwUldSS1RRL2JP
            bWdFOHh6UGNZQVZ0b2hFNXowOGlab1kKdQJ7vB5PH+BSJrn6pZronj6FzsN7QEMi
            dotQDv7yGQOr3N8gMUWg9aR6uko3fqgO7kevxbLgaEOZjV+rRFw4xA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS1JQV1N6YVl0ZW9tUXRi
            NURVSVd3K3I3cmJSM1NGam1hTDkwKzBYM0NrClpGanNaa2xpK21xOWhDSGFLOG9u
            MlJrSFFDYjR5M2MvbzFKbzZYSzJ1UUEKLS0tIFNha1BCZExBUEZURlFvRFBtWHJz
            bnI0bG52ajlGN0FTL0gvQVpDaTVyT1UKXp6s4xl9ivq7HpFb9Cc1pvoDJUanZRO2
            Xk1nImoagoSROECBfe0J1AFkyO+BNBSCewX0XdJEFGtgiaUvw8Ehnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T18:49:58Z"
    mac: ENC[AES256_GCM,data:bVTOoS0pXT2d7O6o1fugQ9wI9DTJq5QV3OcK1HZJ2clVzusQ05Dwib2vwvyxG8RsVsqM+PUIxgeUg8Cg699LNVomb4SV7IiIGj5lIjYsXlmEDYE6FeZxSjx2gioRqRu9j8gTVdnvFnZmszX+w9uTu88AWc09V1rZu1o9xznHRpA=,iv:v/+Ud9MnxDSv6kAR3hm+1JvNJYf+S0ujPoST4QRdnoU=,tag:ZjCjUZvBJxhMD7t0UhwJbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
