apiVersion: ENC[AES256_GCM,data:Aos=,iv:4IGAulxAtltBSw9XcwVwT7BcVQulMjaJR8ZEac7eCbE=,tag:s1uD4qfVpsVLqI+l4MZ7vg==,type:str]
kind: ENC[AES256_GCM,data:PvTV9RrA,iv:lLsbYIOl+cEqKvhjbJo7GeFk1mUh9HWeHZE46TDpG68=,tag:apfUnHoDecRB3/NFZD3fgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2K6G6Kf3WFT65vccZ9cqQgpNSyPLlJS/,iv:sXfbIhHOkWB2JBrkSdxUooc5w8xvsq5FooQhhOceuhs=,tag:kmiqbruFSR6mUkB4vrnrJw==,type:str]
    namespace: ENC[AES256_GCM,data:SXEG7WasPFe7,iv:gqv05pcGXhb6wvpBXz9111Dg/IwkB6kKOXBwhENh+/k=,tag:ifVNFOuD2bvfg/UVYZi4Eg==,type:str]
type: ENC[AES256_GCM,data:xCP6dluB,iv:v+rwe8WxwW/38SPQoTzzMxFQrjx8WZZ6t6pHIk5b+qU=,tag:KJ/WKzHYtnpIZ4Ou6UwM4A==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:4YXCEYlrNzuWNGSzjogetOzMA/g6aSqa5tYVoV4D7hf/dYbgbUqdnmn9i6XAxf09nGCcsKyoUIwKViyrvCZyT5gJ5BSn7ljQDzCjIYhmBnUol4hmML6vGeosbdWiTB2wxD16WYSTxJMukyZdgbnJqCw3B6ah,iv:2hHxRIVQJk3wV+1b1+HSdhQ0PSqQKeAHHXO4re29qbI=,tag:yhImJn6m6cv8B7q1RtD7iQ==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUkZ3UEFZSEZPYlNXWkZ5
            Nkc5UTlPd0NqWVF0cjhDak5vcW1LZDhObDFZCm5UZHdEZDROVzY5VGliZVI2MlFk
            UEdOdytwMXJmakI3NjZUN2dTZDlFSFkKLS0tIHhtd2VrYWJvTm8wdFhTUThyV2Fn
            N3J2aDRBNjZvZGR6MzdWZS95Sy9KekkKJFQivyYqPll7f9kDziOfPPiDPBGR9nIh
            u/gukoVKejy3C3OkYD4/5GYBXacrqd8+Ar/Nwjq+RVgXzRHR05/CsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z21CclNkZnFqdVpDYWVI
            S3pIT2pZSnhkVk4wZVI3UG1PYWE1UUtlS1FjCldmT1oyOVNZejZXaDRYVXJSRWlT
            bldtMUtXWW1pN2djTjB6NXAxRisyZ3MKLS0tIDQ1T1BGajNqUzhJV1VydHZCRmVT
            REMwVWpQV0lQTmxNYjFMZDEzWE1RZ28KwA8gJzxlPbQYYq+iruOQdzwOHE8s4YRh
            xnN1JCwtJawzhrMeh10TAADn8RMD3SplG+B5XeaYBWLveHNNoaA8eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T15:06:03Z"
    mac: ENC[AES256_GCM,data:hv01usjztNR5PrlxOkgo0Y072q7zcHmFAQfdEPEb1rwZBGEQ9f06JnUnCin2ZBO3fxleAPwkQwrTf39flgE9uZpxlG5PD7KZhB14EJ6tf/i50bMvn/10T7e7VBcWOzdPWAbPSsRZkB8KzZPGnlxunqaVV8ja7DqG2J/l0mfTwvs=,iv:bLFOFSaXdT+j7BFX+/3vv89q6G1yxMB6248CBQUfVd0=,tag:XwnCM8fF7xutZ0eSc5rLfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
