apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - model-sync.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secrets.yaml
