apiVersion: v1
kind: Secret
metadata:
    name: huggingface-token
    namespace: llm
type: Opaque
stringData:
    #ENC[AES256_GCM,data:VgkkYAFOOMxzjiN1i+mjyZMpYgXj0TmReatWi1TFlb1EDj340PebaLx8SegGwjFOSGRexi0Qk2USL1VU2I1PbIM=,iv:bxaq2NViSm89M4Twk6e0d7AGpsCmCC2VvOgt0IPxF6A=,tag:vSKPijPOGavW7/ejZ9ZkiA==,type:comment]
    #ENC[AES256_GCM,data:ILtiHuUY4ajJRQ3lvhyRKlkS3O6GaOGNT0z/HCQ42vMQmdGPUbnWGMZF,iv:iBg+a5/b1bEIqREZONnK4XzpoEsMExq2BIH3QLD7gA4=,tag:GMhlbjrzNzGbf+VpU/2jGw==,type:comment]
    #ENC[AES256_GCM,data:njxaZIlydB0LZPuJXEgGH8/y396HMJZkTHAxcXWyZBPvekzpU9J8tqUwzH8L62/zl5g=,iv:QOVn/rDBasHbw3V+HIaieN+ncbekH2JMDqCsEgqctrQ=,tag:Ojnp4l5dxDm3ee1jnVQJgg==,type:comment]
    #ENC[AES256_GCM,data:r+DYnemC5A+/8TziUzOTHmP2geuIwYcGKJU6W/ytaKu4D5sU9brRBwGDAeGP8vEoGoTcImiQgybIjVer9M7zZQ==,iv:BO8JKWPjAv4nBkD1WLLq4woY0cFrAB1JjN3TFtekidI=,tag:TQpScfsmUjnl4t26YVWxiQ==,type:comment]
    #ENC[AES256_GCM,data:T9z+9hLyUNTqQfpDKggZFo68SOEgd/Ub4qSZ/4zuXnjB,iv:QHS5/NTs9Qhx4nmqxhJ9Fj3rvGur2k/G2wVJopoqN9A=,tag:NsUFHx8DoMqc154Si9kxqg==,type:comment]
    token: ENC[AES256_GCM,data:lVqMnHw9dvpm7Gd2kN5q8gvRMoJCyy2YUoMFvPaqDUh8wvKGKw==,iv:y1FaGlT4SMlShpFLdopEZO1X4c/ocD+lZbwwiGQZ3DU=,tag:aXBfDzJD84IM0lRp8tWH5g==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOHphQ2d1NlZMWSt1QlVx
            dU1YeXMxY1k4R1RZQms3eCtzUzhwRjNOTWgwCkpBOUZwZytLSkpmWTM5S3hIc0JV
            T2kzVmVHRW04Ykh5WUZaWUE2UnRYZncKLS0tIGptQ3U0YTZheS9iQkFqR1NEdHFO
            TmovS0lQdG5Lb3BvMExLY0dTNll2KzQK2YLR3DFw77M7WYB+IU029o5tSqwgf2mb
            xO/tSNI7SuoO5nJeCDre2Wssn+GEmbpfILVU3fjrDqw4SnpiN8x6Jg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVmE3eFkwZ2tZS1dLUnd0
            QXZRNitVSnJpb2lVeDM0eDdjZDZSRHJaSEZRCmtZUEs2alRYYVgrYllRNnFHOW41
            aHk1V2FMcysra3UvRzQ1T1FLWUNqaWcKLS0tIHh1QVhNVzdaVnlWTXVVRklqczk5
            THNiV1VyVDBTYm5kUTBtL0VpeHluWjQKgGZR+2Mwv0k04AUYaLjMrnxvCyqRPZDO
            AdA7iVyskdM8+CoH6lunLb5ZWeYUk5qzLOKmCP42LdVzwwGc/hY1aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T11:53:41Z"
    mac: ENC[AES256_GCM,data:Pwx3nRvuMTnbvREJwRehibMEkU6d7ZXwdg7aiLIYwEgwliA5qA4zQfOuK2vT/8whX0XZVAPFL+ZE1xpU5YYivgx0u8ZkKAeZAvlQoJeOOPX2jeKMuw9du8veNi9D2cfGe+dfCn3OBhOK4B8l/ouB0os2FoU7GuUm0jqJ+gE606k=,iv:6+hD6l0EDilhFogUzTWzRUuFTWY1yaADG+GPmm03ZtM=,tag:sFBCV5GETgba3ekmZo3u+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
