apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:yjXCFoA82Ij5CMu9tsU9zdOD7bNjGx+0Zn3b/v8mLpOxRD8gnE6KGXgoS0kGWAaGSxlTNqliC4byFEFQ4k27Na7N05LjYpXZBHU8I0n3mv2JuI68lBpLJEkJ1FgKFE0yJ5rf3SBLuh+K0H5j+JKdlkC+z4qF,iv:YfyJxFv0gj0/VtXpzpYQmmOzxPpFjXid41QSNHwppfE=,tag:QlEUyprnrxlHu/mWUNyLFg==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOFBCR080RDRPd25zSVdV
            bkZlcGZNRGNHWjRqMXdDVW0wZWRBR0hpeVZNCmZtMUVFQkNEUnduM01aLy9MdDhz
            cGVNaGpwTW9PT1JxZWhxcnBweE55RUEKLS0tIHJlczJTVnhDeC96U3BKUFd5OWcy
            ZitmblVySTRvR3pzeWNCT1RVU0ZzUTAK0TGuOwq7uT1JRb0yijyWhGzabfD7fmyM
            sWCKtLBphkXcZrluY4PQc+Z/RW3zV4B8hkvNomaWDQFlblgxGY8MUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmL1hDeFo2bUhOcFd6K0JX
            eFFHdEJLUkc4R1ZsMXJpV1dUZ2RpSStCK1dJClBDTmE4dlNZV003bXRuQkQ4Y29v
            aTBNTWZRcFMzelU0aDhFcHlXU284M1kKLS0tIGxMNzBmQVdCd3Z3OHoxKy9KcFVU
            RUpuQ1kwdllCa29LUnFGek45Z3lNWEEKK6LS+cu4zTXzGcxNp9ycI8I8zGERZYU5
            k8LQv+/ckZG1eg51iDzAJERCj4lflyyroNpI9kyCAwzSjh3Zt7YEiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T18:59:41Z"
    mac: ENC[AES256_GCM,data:RfAiIEaBEZlbicj8sRjCWbsCuGBMAix0FuBUpqr1pTv991m19f/6xGbkLxdZV++Ajs2rnA8YaaHFYrlfmlaDfHiSjucYtnxNLraPj5TTaQmDoeH9sK4howE6nf+sEFwzXA/PorSGikpsyDx4WH1zZAEw66u6SXqCIy186GMsTHg=,iv:Z0Z/vUvNXNZCYa0xdJbEdYPzpumHOw14Q+p4EnZ25o4=,tag:DdsJ6Mxfsl6KNzGpS003RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
