apiVersion: ENC[AES256_GCM,data:ENE=,iv:9yHfeuRjRPc8QfTl/IXN0DXcLvBmWRdiCp2kHrSre9c=,tag:ogqfQQbW9NNB/bI+vgTObg==,type:str]
kind: ENC[AES256_GCM,data:d1Wo3dfB,iv:NKa8mYHWAkyGKiyXlYMLLQC1A/gsHvGgBH8gRjwaTFY=,tag:z60UhStU2BuT+BBwWFUyNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5gOKnvg=,iv:s9QK0RxHvmsm9bLi/90KZtKD2T0Nvbr160yAlxGixWE=,tag:i5qzOM6eXqgWsZqShwWaaw==,type:str]
    namespace: ENC[AES256_GCM,data:MPdVEC4=,iv:sGXpc9G7DdWhTH+4yRE4JVvXLAiazenog+XURlzUAzQ=,tag:jhEzu/7Nb3hXRi5rOkF+pg==,type:str]
type: ENC[AES256_GCM,data:MXfmWFSR,iv:SnN2F2t64PyDZO0eRhFd4M53fh0anK33EHQlNV5YzAM=,tag:j1TQBEAwNAt9qYJPhzxQUA==,type:str]
stringData:
    #ENC[AES256_GCM,data:qoOXwDlwdW3DascwkoUCXTP1ewyuYFYZAOXMuJWzaFZfj3PcqrOY6uhHS9DnLboYn9je9jQd+UcLukbRgPY0H+RJ7JkxzBeZq2kQ+g==,iv:w+71tfwkmYaXjSkIeluM8Ihm9bmtYDbd3t0xf7ii05w=,tag:FiVyFg/Tzg+TFvhW92yMng==,type:comment]
    db-password: ENC[AES256_GCM,data:3U73eNW/E/wkOZ3eHLAAs+oJccqusZoG,iv:FEbnEveETgK3bflPkQ3v/OEQnAG9+vgaTx3QPlA5Mnk=,tag:rIAevRUB0LJWM/mHZLgYIQ==,type:str]
    #ENC[AES256_GCM,data:LJlzSv2+b7YDBwOng67Hy2QXGH9ymllmTD5l1B+ACGsSGZP936d1uH9C872tQRwbBkUKGQB7inzm403n2Znbd8TjdRCvl8otVYLpgy4=,iv:XbYIMZbZNBlfptH+1IKc1qM7NTdBPniHBAInJynMtyc=,tag:T+gspNmHwWYUEg0G1rzvfg==,type:comment]
    app-secret: ENC[AES256_GCM,data:CyI2eVgvXTzL/8z3xjRD8WKryF8xYHC0,iv:CspY4IhcK/QDoyjvOAIO7siWrE0Dqwqra/83PssBhSs=,tag:wcQ9oN4alS7vxo+u+7i/gw==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdEttaHhHRXhlRlljUnda
            bG51M2RpbENTb0lPVmUyWXNzQ0FycjdEdGcwCkhqRDdacnN6bnFBenZBYW9KSnN5
            U09ydlg2ZDRVblJ3czBiOVBBWjk3SDgKLS0tIGhiL3c2bmhFREZBWG0zK2hwVU5I
            eldhQThkblVZM0hUSTJzcW5iTTVkSjgKWVInqYpjA+qPLwNuxOi4Kv4RzJXDIIuQ
            1Z1RdpKXh07DGL5Pq9atrjdIiM8d/xkp2s0O4Bwxa++Dc0yeb/bijg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QjdXdm44MzFEUW5KS0xM
            Ky9BQUM3SUZHQnZaTmpGS1IwSktPRVVRUG1JCitnWkY2bHpLQ2hrcWo1WWhsakR4
            aEpGV3BTOEwyVll5dlBoamR6WTc2b3MKLS0tIDhlVlQvZml5aXdhanNkV3NNQ2J0
            a1NGZmExL3JDemJER1RWTm03Vk02Z00KNuTLBuzn4gN11DbpC+Di+2pgPF1Oh38I
            JisnvHI/qM1xMGcxOjiJdNIHbDh0y/aZwz5vEEPTyYwgMK9ucVFB0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T18:50:44Z"
    mac: ENC[AES256_GCM,data:AnOzWaswhUulQxOTjzTQudCb8bmdsmQu0afnsbyOZocU9KjUdlm8KeitombNCcgcnE1+M5IGUZafSeI5xoq0vuXOHXGuE2lMCTYNgHZY1MquYS1XreIRbv4MV2BzHC6fJ982rt6Bpm7Fkpmqew7ckGKAaDChXDPrswITZt4oSzk=,iv:lR16nf9oGHrClWcwZ4qJOgjwzTSiFjaz5NSgONXqOlM=,tag:FNF7ho35lYHcg3L0lfNmrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
