apiVersion: v1
kind: Secret
metadata:
    name: umami
    namespace: umami
type: Opaque
stringData:
    #ENC[AES256_GCM,data:iUoVosBy4QBZ7BrZk8Dojp364e0bJX+MMCekfIgdqLcgzTExFbU7d6ZGExIdCQ7/Ju5x2lzpG3zwRGfWgyt2Qsl64B3FuHQXYfHq7g==,iv:s34ylAlabT1e37iPr05h4v0NQLXsn2ILrVRBVl+1nMc=,tag:SluMENWPZEPYDIhuhZ1X6g==,type:comment]
    db-password: ENC[AES256_GCM,data:RLI80DCzkEWMOzFZTNmjxZQZVE3ZLOqWEXddVUK876D9NoEfgV7un/clO6//OWmud3cBGpU+4ko7almiLLpsWw==,iv:mlFK2moPlmeKxHEj4jX6RShNeXwBgWHdkHDGNu4hZOs=,tag:6xsx51Du3R/+kePdgBZUxA==,type:str]
    #ENC[AES256_GCM,data:B/iTjsydQtHLdyWsLDd/Zx5h8e1zarCP1CeF7Xgl2EeW/nmKrVFAVdEQ3B+kBem9cdPX67sjFefORXkp6QkW8PzbQcOD44Y5WimjfKw=,iv:b1G78QuvEXTczVS9RPlbp5oZfmO0M0Fmyw3uH8ZqAMk=,tag:RCTjjtz6JERTVZJxMWBR+w==,type:comment]
    app-secret: ENC[AES256_GCM,data:5YURPnMONvIZNJioXQ8fg52UPq9Ofodhu65N7cLS6JkNCgSXKMs/FBTuusLPf2PyJFC8w88l4t6LnJwoFN7Xgw==,iv:fTHU/gMP6C1RjRGbxZeEQiiq7T5QLDNauwBW4au6lwc=,tag:xhs/0FyXddcw37pNvZH0dw==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdzFQMklhc05VcG15OGtu
            Z0FJWUx1eXlEejI3QXZ0TFlCd2pjOU0vMDNJCmYzMW43V1ExWEJKZkV0d3ZBb1U2
            QkRGbjN0TFp6N3Y1UzZraVFtLy92Q1UKLS0tIFA3VG81K2ExbjJJc0YvS2JmWWRT
            RndZekdrMmpjM2RNT04xVm9PaVZqQlkKi3g+UolPIRtxFmhqs5KUI/1mKscA5u7I
            LfuyTGW7FvdlCIco2Ka52iYRcy3X5LIU8/vsE5GveflBPn6zITqEyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESTZPQytrSythSXBXaUl3
            MlNpMm9BWktZSVgybnpacHI5a0RmczlkbWdNCmQxclVJYTcvaHdIR3VmNGY3OUNj
            aGFUR0UzaVBoeFpwYjNNZmdoZCtMVFUKLS0tIFVZTk5ZNFZJTGhmL0RvS3FPTmhu
            QlB3a1lnRWIwaWNWWEVFbk5EcXdUQVEKB3bH806422+jZ8cOdakdjzCjnEzc/NDx
            J02TBfEaZ5GuJzNL46R9+jvYMbXXhrd5Btj7Tgjpr/3S+Fkg8Z3dtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:31:12Z"
    mac: ENC[AES256_GCM,data:59D0Ol0lLm0Fg9G8xGGgKEKoxNOSOuJfrVH6SNBROdEHO/GIEtV5gRHm5cVFL/rIbbEyAPmk4mB3x1xbU6Rb9i/5mr4vnJaZBdw7HCvN/41qbNPahaCvwt7lWyjf1YXskWCKphct9451eGsgndKNh4YUt8tK15qyFFqntl+ZNug=,iv:S8P75RBIxTxcmUZXykuRK27ea3ebEDTIIRKfLRK44q0=,tag:NEE6tBXz3/8jDFBIcmEHdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
