apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    #ENC[AES256_GCM,data:zxKyU2Cwr+plBalhTAjxpNXetFH/viZEOtw7Juen19MQ2wTbNOXl7ezK9hcQzUvmSKmehxCy42wKUb9Qjuu0rx0=,iv:zZsxPx+1B9UNQi+FSl/ZWB1NuXuBSnfcmnD+d8+pTjU=,tag:8DdYoEy7U5zm25+r9x0YaA==,type:comment]
    #ENC[AES256_GCM,data:Rsx0SEgM9OhD/67jVJUke7Fl5O+3tdjQ1XvZ2mzykahR8f7JBvuctxOTfvzn1ZyLjP6WAFP8nje4ovvxVuM=,iv:hLqqAIK0ifg5aUG/J1ItA/71Y70PPhMuttSEPjnQgh0=,tag:8Wj/lT2bptplZwmxwssbWA==,type:comment]
    #ENC[AES256_GCM,data:xssaMFcAYOzvU/1chCwu8F0ArmeJB+awGfuhTr5hXPSJTyadJCtgC017u/vpwDmTkbCMG2w=,iv:hrrP+xXHMEDIUxN94MSVbMUYVB2PspwOzB/NXlZMKXs=,tag:CTPSkClt6i/Hw/QVTUrObw==,type:comment]
    api-token: ENC[AES256_GCM,data:4EHj8E5le4yx9j/jT35j0uUWSO+nN35Lt2pqGKo2evo+5yezlwx3eGkcKVi+WtNmIq/tQjI=,iv:yI2mPbgJ2+NdtuKFCKA6Sc9rOacP4MelOVvpqUCS8kE=,tag:fdLsRZVswhhWIp43X7uncw==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUEE0bC9URmw4bTdBVXlk
            MUZXWXlha2tUM3QyclUra3B0bnRzRFc3bmdrCkZmbWI0WmRCOHhrYXlkWDlFcXRX
            TEdDL1doZmxacSs0NS9ubkE1dHhlYXcKLS0tIGl5Wmx4UGFzWmRhNmhTK2VnWUZP
            aG50a1FYWHBhQ2hEL1dXbEd1VDlMeHcK0EmP033RKByqJUgU8/lC/IDHJDSuYjqM
            sVWJ/PTGUXdTovqLK25ppsNsdFyHHaJZrikSYE1oPQKRw4OCzqN7Ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWmFDTCsxTDRzTmt0bTJq
            c2RHRmRoWVVjM3RER3Z2NnRXUkFYd1ZkZTB3ClE4WVRaQ2hEN2RxVXg5aDI0c0hu
            TDFCOTFHZjdVLzJ4VGpHdHl2eWVOTncKLS0tIHorZXVwbG5zRDIrbDIzYm9xbVAv
            N2hZUjF3VFFJK1FmUHZHRklBb3lsWnMKL8lYYE/gWRKhsVgyzIqb7cacUwlQtUZu
            IUDHuSqbj9MWSX5QNz973VHcirh1hX61sk5UcNGiO+5Ud7j4nAuuMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T18:59:41Z"
    mac: ENC[AES256_GCM,data:QsFpI+EC/s2a23y8UaL7/Cc6Bz/B2WmhQMyvTdv4PRn948wvn1ZSS79k+oHwtMI2OMYISnRjT/iYadv4uM3QE74qXwQCrsbFSBDWuwwte6mGO/3Qtg2iSFnIf+aZ0heMsLXEru1LunLQodpiekRVE3gvqe+TbtONz+x4qpY6ptg=,iv:aEwaib4SOdlLmJbmrLpK+SODe0vwWDVrHV900AX5Z1s=,tag:R9sDjTvQfa9qODmwOY3FYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
