apiVersion: ENC[AES256_GCM,data:3pA=,iv:5VUFmgMYcJUlV34RnorhPcYTsse1h9PJYJKMRL8rSHg=,tag:9jsw7QQrHzpZ09VCTpIovw==,type:str]
kind: ENC[AES256_GCM,data:3EvHx6Yp,iv:SzV1TSdM5D6LBe4HLq0pi0ie35ZvzbF1+pkbSQcfh70=,tag:hniq5mLZ7Qt5u1o2fP10Tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EMq1TRbHHtl6DmNq+iX/kfSkKuU=,iv:154tG5AiEhOCVmAhKycoOsTlYeVvfALHVVXaKTMPXzc=,tag:5Km7b2uogGkN04iAvok06A==,type:str]
    namespace: ENC[AES256_GCM,data:Hc9+oecoLoArzgue,iv:A02/dASclCtXshTMjfdmMrxVTJ53ynvhnjfEuxjybd0=,tag:qYmVxtWxnKN4ba/2BP7enA==,type:str]
type: ENC[AES256_GCM,data:9Wicey1B,iv:0VZdlr67W3IMzZYPcKczqbdTuJvnVx3fpf9LsUun950=,tag:XtfZjJ1ossUG5HPGbmxn4w==,type:str]
stringData:
    #ENC[AES256_GCM,data:Z+oPus1JYJZE2FGozsvS0k7CMOmxIGj+va8N0t1fI7w9m1aC3kMZG7rluZnAtdVfEYwyMlllmZZsiWgLuxD0toA=,iv:CwfQoxZyyBGSEKnTZvo5rrKIzarJdHXPzKCf2hKZad8=,tag:NqwNALc+iorCnJjhm4GO+g==,type:comment]
    #ENC[AES256_GCM,data:419Cq4pTO6WtIOQOvtwG8dTO8pJFy0QXO4HvIvXEOopc/dR9634qfyXLQT2QHbBJngEd7FK65w32+H7i4xw=,iv:ZkKZSHlOh94eQMWrkMEnGk0g8ya3XSRPtYrfO9L6JoU=,tag:/VWm2MimGfv/DTJ1uhv4Jg==,type:comment]
    #ENC[AES256_GCM,data:0VTnnuCs3HdVNwIUQuBeea/fbWm/rYTsUbyn3folzrQcMoxsTLxr+mcboJWK9fYqlI6nnMo=,iv:4+CR8wuProTDu/T3Fix3piH7SR3mWisFSLrMgXpUrlE=,tag:3eGd7Ro2QsIwiXAhlWS8nw==,type:comment]
    api-token: ENC[AES256_GCM,data:zCBtN9p75k7qp5Usra2NDXXErTMTSNmVCWdT/fD4QyeOoSPmkOLYKSP3rmyXjcZlEoAUGpg=,iv:/fnd91U3aqm25+4LwFfA5HI/cjVdRkNPqRm6fi98pX8=,tag:I3pUb+8+EAgciEw1YxfJow==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Mk1vUmRkU0hWb1g1c2x0
            QVl1SlZzY00wQ21vUlJhSjBsK0FkQzkrYVRjCmNaQU5vTUJyNjhBMEpBU3hib25v
            N0RaVkNpM2ttNVFmOVdPeGNITUpMenMKLS0tIE1pdTQ3a2ZNeWpkQStDdEtNSjV1
            OUE5WWdGQkowM3U5bmMrQVEzTEI5NlkK1/d4K6frlOFjwHqzioeA6B8T4cJBMGFP
            8bly5XcP8rK0kYCV+NRoFjLAfGfQNinRcEvuE8rlotwy3ospd5JHbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdHZuVjVlMC9sLy9OR0J2
            cjJUakdUbzI5c1ovUFlaT0FIdmJMM1FCZDIwClZpRnpTL29Za0FieGdsOHUwbUh1
            TENBMk5ObHc1c1pBZk1COU5FeGIwOUkKLS0tIEVTS2lDek9MZG5HRTRVaHBWRFdT
            M3dtaW9aVzRpbTIrcFJlYkFWYnVhZXMKPQJe7IEarJrTw3EORIckwvg3LfBn3H9O
            gLx+iDhxkGrv05JltYCmy44b7fayvqbDdeXGwJQZck5fNS6ZMMF7bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T12:03:46Z"
    mac: ENC[AES256_GCM,data:Ec+L20e5I9EBDgrKFD/wWRFDqbgoVKWRYKc9Y9JPD91TW0tHG2RK4T9Wyvw6JY6HegR98fynbxR8IOppYuKm0kRUuh/kzMxHsm6CfUDJ1XbIf4vUSbGwC3mSK3VSp0kACuvHfP2m/SfGWrgtX5iM0DSa5FUGfUp/gvO745aqn2Y=,iv:gb4Nxd3i8dP+RgGKUR0rQ/e+exw57Fhz1YwsIOR/1aU=,tag:nHdJu+vCEjowy2FsCncVXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
