apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:qZgnFF+7Xbt8UiuzGz2o+w0MTosrqVTwS+eriggjJdtLtzH8OyondhfXcFqb9bheuaP1Zj86OrNoP3m6X4eG3eo6tVYfXNJHF/+IkvkE9jQA+3GiXXiBKq5X1v1CgYXATncqwHBJPBBFr9XP92CqH8gKGqovG1suIuygqDkMkRjeI01+D9ZxfY/TCiViCQ==,iv:/SYVb81QyCzM471qMdi0jHQ+RQ6ye+zibwDMjeAJUac=,tag:/84PbZZYb2C7cJP2D+etbQ==,type:str]
sops:
    age:
        - recipient: age14gl7ry2n8ugwfhfjsd6gn0egsyxhf9yudpavqm0h8saw6yuuvgqsvkr5sl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T0U4WDhQbk9uU3pMLzZr
            UFVDODZQTzBreXUwaHBKSEJSMWNjRFRRRG5rCmRjZTBZbDFGM21uTWpjSC9vOWhM
            MDNVRWZXemdaaU41SmNPS2ZJU05NZlUKLS0tIGJDdHZHZVYzU3YzNjNGNk9LalE3
            Nm5xMHY5SnNLVVo0N3pNMXVURTZkalEKhgwwXbua+Uj8I7xX3G9YIX2oPejFZBs+
            HoXRWC2fP7X6/eAhWnBzNx1yyE3P+KlyqaGF8w1vWMKWqjYFbAJtcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17zy9ynlrmqcs4u03hh2echldh7utle2pxs62g4hzrvl7eswyqyuqt8hra9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ujh6QnhDeHFWZ0tUSkJZ
            L0xLL21hQ2NXbjRsMGJPZ1V5ZE9xRE5nOFhFCmM3ei9EemEzQmJxd2VmWWlST3hH
            cFdabVZUb2lCRnZXVEdEcE82Vnl2RGcKLS0tIEp6VkIra3RJOWxQMkErQWhrR3Rl
            OE1QMkxIU2dOWWIrOHdlRTRWT3JxL2cKzc06RJbrgccn7VGpRmwjjo/sO8356Gn9
            RrEk1VTEhZi1bkK/m+mwpTRKhlhJjSdgwbng0Wo2LNzOwuncesr2LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T18:59:41Z"
    mac: ENC[AES256_GCM,data:t2ZoEPj21jR3q3RrT8fKcMz62QQ5T/Z5iPoQZ+HXbxThkHh2BaSExf0W8pTivub927+9TVUhZZboRYYY+FtwFAv0NN6LFJbCmkYnputnWvnacY3njI0wUiX07UMOT17Op5QQuIXg7zPIx3xp6rOxG/g1lYqDX8HHgJSm84xjI7k=,iv:NzN+xpGz7Zm+1+A0WNLK2toXQBDc7cNEXkJ8UIiLx2I=,tag:aTuttHyq/moSwvBC8nBiTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
